homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  time_zone: Europe/Amsterdam
  elevation: !secret home_elevation
  unit_system: metric
  auth_mfa_modules:
    - type: totp
      
lovelace:
  mode: yaml 

# Example configuration.yaml entry 
# See https://www.home-assistant.io/integrations/default_config/
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret HA_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key
    
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_apikey
    allowed_chat_ids: 
      - !secret telegram_bot_chatid
  
# Example configuration.yaml entry
logger:
  default: warning