# When timer is stopped, the time run out, another message is sent
alias: Timerstop
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.anneslapen5
action:
  - service: scene.turn_on
    entity_id: scene.anne_slaapstand
  - service: input_boolean.turn_off
    entity_id: input_boolean.slapen_anne_in_5_min