alias: Zet de lamp in de gang aan als er beweging is
trigger:
  platform: state
  entity_id: binary_sensor.philips_sml001_5ace1302_occupancy
  to: 'on'
action:
  service: light.turn_on
  entity_id: light.philips_lwb004_3688e500_level_on_off