alias: Zet de lamp uit na 2 minuten na de laatste beweging
trigger:
  platform: state
  entity_id: binary_sensor.philips_sml001_5ace1302_occupancy
  to: 'off'
  for:
    minutes: 2
action:
  service: light.turn_off
  entity_id: light.philips_lwb004_3688e500_level_on_off
   