# Example automations.yaml entry
alias: Timerswitch
# Timer is started when the switch pumprun is set to on.
trigger:
- platform: state
  entity_id: input_boolean.slapen_bram_in_5_min
  to: 'on'
action:
- service: timer.start
  entity_id: timer.bramslapen5
- service: scene.turn_on
  entity_id: scene.bram_alles_aan